"""updated

Revision ID: cf412657772a
Revises: 2aa3245a32f6
Create Date: 2023-08-05 23:08:37.854021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf412657772a'
down_revision = '2aa3245a32f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_model', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote_model', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
